### ISSUE TITLE
[FEAT] BusSeatMission 장면에 흔들림 추가

### ISSUE THREAD

**Issue by seodam-hst** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#15]
**기능 설명**
작업할 기능을 설명해주세요.

**작업 내용**
작업해야 할 목록을 입력해주세요.
- [ ] 작업

**참고할 내용**
작업에 참고할 사항을 입력해주세요.

**기타**
기타 내용을 입력해주세요.

**Comment by JungYunseong** [comment]
화면 흔들림 효과를 주기위해 [SKCameraNode](https://developer.apple.com/documentation/spritekit/skcameranode)에 대해서 찾아보시면 좋을 것 같아용~
