### ISSUE TITLE
[FEAT] OrderMilkShakeScene / 밀크셰이크 주문하는 장면 구현하기

### ISSUE THREAD

**Issue by seodam-hst** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#47]
**기능 설명**
OrderMilkShakeScene 장면

**작업 내용**
- [x] 어셋들을 SKNode로 배치하기
- [x] UIKit으로 더블 탭 구현 ([Double Tap Gesture in UIKit](https://www.hackingwithswift.com/example-code/uikit/how-to-detect-a-double-tap-gesture))
- [x] 더블 탭을 눌렀을 때 뛰는 모션 만들기 ([SKCameraNode](https://developer.apple.com/documentation/spritekit/skcameranode))
- [x] 점프를 여러번 하면서 흐릿했던 메뉴판이 점점 뚜렷해지게 만들기 ([SKEffectNode](https://developer.apple.com/documentation/spritekit/skeffectnode) OR 어셋 여러 장 이용)
- [ ] 사운드 및 진동 추가

**기타**
- 예상 작업시간: 8시간
- 실제 작업시간: 6시간 (사운드 및 진동 이슈는 해결하지 않음. 우선순위 높은 다른 이슈들 먼저 처리할 생각)

**Comment by seunghoonkim34** [comment]
확인했습니다.
