### ISSUE TITLE
[ASSET] CafeRoad, CafeInterior, OrderMilkShake 장면 어셋 그리기

### ISSUE THREAD

**Issue by seodam-hst** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#48]
**기능 설명**
서담, 네이스 작업에 필요한 어셋들을 그립니다. 

**작업 내용**
- CafeRoadScene
  - [x] 배경
  - [x] 카페 입구 1 
  - [x] 카페 입구 2
- CafeInteriorScene
  - [x] 배경
  - [x] 주문대 
  - [x] 테이블
- OrderMilkShakeScene
  - [x] 배경
  - [x] 주문대
  - [x] 메뉴판

**참고할 내용**

**기타**
- 예상 작업시간: Scene 당 1시간 -> 총 3시간 
- 실제 작업시간: 총 3시간 30분

**Comment by seunghoonkim34** [comment]
확인했습니다.
