### ISSUE TITLE
[FEAT] StoryView

### ISSUE THREAD

**Issue by JungYunseong** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#6]
**기능 설명**
GameView의 왼쪽 뷰인 StoryView를 추가합니다.

**작업 내용**
- [x]  장애물 피해서 최단거리로 걷기
- [x]  드래그가 아니라 탭으로 이동하게 만들기
- [x]  탭한 위치에 O 표시
- [x] 탭한 위치에 따른 player facing 방향 바꾸기
- [x] 배경 무한 로딩

**참고할 내용**
SpriteKit

**기타**
기타내용을 입력해주세요.

**Comment by David-ShinDJ** [comment]
위의 작업내용 리스트 Projects < Git칸반에 업데이트하겠습니다 그리고 추후에 추가될부분도 깃칸반으로 추가하도록하겠습니다
