### ISSUE TITLE
[BUG] Image Assets 해상도 수정이 필요합니다.

### ISSUE THREAD

**Issue by JungYunseong** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#7]
**버그 설명**
StageView와 GameView에 들어간 Image Assets들의 해상도가 깨집니다.

**재현 방법**

1. StageView
2. GameView

**원래 의도한 동작**
기기별 해상도가 다르게 적용되어야 합니다.

**스크린샷**
버그가 발생한 장면을 이미지로 남겨주세요.

![Simulator Screen Shot - iPhone 12 - 2022-07-16 at 18 08 43](https://user-images.githubusercontent.com/95982751/179348520-9a556c95-884d-4cd7-ace3-40690def3e24.png)
![Simulator Screen Shot - iPhone 12 - 2022-07-16 at 18 08 40](https://user-images.githubusercontent.com/95982751/179348516-3b634b00-89d1-444e-8348-150f459db56a.png)

**버그가 발생한 기종**
* 기종: [iPhone 6이상의 기종]

**기타**
기타 문제가 발생한 상황을 알려주세요

**Comment by David-ShinDJ** [comment]
https://appicon.co/#image-sets

혹시 ImageAsset을 3x 4x 비율등 여러가지비율로  생성한걸 Asset폴더에 넣으면 해결될수있을까요? 
위의 링크로 ImageSets 으로 생성한거 한번 넣어서 확인가능하나용?

**Comment by JungYunseong** [comment]
> https://appicon.co/#image-sets
> 
> 혹시 ImageAsset을 3x 4x 비율등 여러가지비율로 생성한걸 Asset폴더에 넣으면 해결될수있을까요? 위의 링크로 ImageSets 으로 생성한거 한번 넣어서 확인가능하나용?

넵! 그렇게 수정하려고 합니다. 감사합니다. ^___^
