### ISSUE TITLE
[BUG] 가로모드 고정

### ISSUE THREAD

**Issue by JungYunseong** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#8]
**버그 설명**
세로모드에서 지원되지 않게 막아야합니다.

**재현 방법**
앱 실행

**원래 의도한 동작**
앱이 가로모드에서만 지원되어야 합니다.

**스크린샷**
<img src = "https://user-images.githubusercontent.com/95982751/179350018-d34c6eb0-58a3-4865-9c1e-61acefcf85dc.png" width="300">

**버그가 발생한 기종**
* 기종: [모든기종]

**기타**
기타 문제가 발생한 상황을 알려주세요

**Comment by David-ShinDJ** [comment]
https://developer.apple.com/forums/thread/110064
위에것을 참조해서 landScape모드를 강제적용해봤는데

<img width="435" alt="스크린샷 2022-07-17 오전 1 15 17" src="https://user-images.githubusercontent.com/82954337/179363147-8bc746ad-4006-4ce5-acbb-3a45df695a71.png">

위에처럼 조금 불친절하게 강제하는거같아서 디자인수업들었던거 생각해보면 
일반 가로모드일떄 아이폰을 세로로 뒤집어주세요 라는 화면이 나오면 좋을거같습니다

**Comment by JungYunseong** [comment]
> https://developer.apple.com/forums/thread/110064 위에것을 참조해서 landScape모드를 강제적용해봤는데
> 
> <img alt="스크린샷 2022-07-17 오전 1 15 17" width="435" src="https://user-images.githubusercontent.com/82954337/179363147-8bc746ad-4006-4ce5-acbb-3a45df695a71.png">
> 
> 위에처럼 조금 불친절하게 강제하는거같아서 디자인수업들었던거 생각해보면 일반 가로모드일떄 아이폰을 세로로 뒤집어주세요 라는 화면이 나오면 좋을거같습니다

이미 수정해서 풀리퀘로 올려놨습니다. 풀리퀘 커멘트로 달아주세요
