### ISSUE TITLE
[FEAT] BusStage 게임 흐름 매끄럽게 만들기

### ISSUE THREAD

**Issue by seodam-hst** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#92]
**기능 설명**
BusStage 미션 연결되는 부분 매끄럽게 만들기

**작업 내용**
- [ ] BusBellMission 까지 성공 후 다시 앉으면 미션 BusSeatMission이 실행되지 않아야 함.
- [ ] BusStationMission / 확대 후 화면 고정, 터치를 해야 다음 미션으로 넘어가도록 변경 (현재는 성공 이펙트가 보이기 전에 넘어감)
- [ ] BusBellMission / 1.5초 정도 후에 미션 넘어가도록 수정 (현재는 성공 이펙트가 보이기 전에 넘어감)
- [ ] BusSeatMission / 1.5초 정도 후에 미션이 넘어가도록 수정 (현재는 성공 이펙트가 보이기 전에 넘어감)

**참고할 내용**
작업에 참고할 사항을 입력해주세요.

**기타**
기타 내용을 입력해주세요.

**Comment by JungYunseong** [comment]
미끌매끌
