### ISSUE TITLE
[BUG] BusPoleMission longpress하다가 tap하면 로켓팔

### ISSUE THREAD

**Issue by Eunbi-Cho** [DeveloperAcademy-POSTECH/MC3-Team13-RiceCake#96]
**버그 설명**
BusPoleMission longpress하다가 tap하면 로켓팔이 됨

**재현 방법**
1. poleMission 중
2. 마지막 미션에서
3. longpress하다가 tap하면
4. 팔이 로켓팔이 되어버립니다.

**원래 의도한 동작**
longpress를 하다가 멈추면 팔이 다시 내려가야합니다.

**스크린샷**
![IMG_7CF0AC74A4BE-1](https://user-images.githubusercontent.com/98628614/181798224-3f5cf041-100d-4a53-81b9-240e4d75b89c.jpeg)

**버그가 발생한 기종**
* 기종: 모든 기종
* OS: iOS 15.5

**Comment by seodam-hst** [comment]
버그가 남아있었네요 ㅠㅠ

**Comment by bee712** [comment]
끝나지 않은 로켓팔의 저주... 🚀💪

**Comment by JungYunseong** [comment]
푸슝~!

**Comment by seunghoonkim34** [comment]
수고하셨습니다~!
